apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-app
  template:
    metadata:
      labels:
        app: movies-app
    spec:
      containers:
        - name: movies-app
          image: aksautoregistry.azurecr.io/movies-app:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: movies-app
spec:
  selector:
    app: movies-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies-app
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: moviesapp.aksauto.azure.d-sancho.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movies-app
                port:
                  number: 8080